import {APP_IMAGES} from 'src/assets/images';

export default {
  home_tag_list: [
    {
      id: 1,
      title: 'Hot Coffees',
    },
    {id: 2, title: 'Ice Teas'},
    {id: 3, title: 'Hot Teas'},
    {id: 4, title: 'Drinks'},
    {id: 5, title: 'Bakery'},
  ],
  drink_list: [
    {
      id: 1,
      image: APP_IMAGES.ic_arabica,
      price: '$18',
      name: 'Arabica',
      desc: 'Lorem ipsum dolor sit amet cons ',
      isFavorite: false,
    },

    {
      id: 2,
      image: APP_IMAGES.ic_robusta,
      price: '$20',
      name: 'Robusta',
      desc: 'Lorem ipsum dolor sit amet cons ',
      isFavorite: false,
    },
    {
      id: 3,
      image: APP_IMAGES.ic_excelsa,
      price: '$15',
      name: 'Excelsa',
      desc: 'Lorem ipsum dolor sit amet cons ',
      isFavorite: false,
    },
    {
      id: 4,
      image: APP_IMAGES.ic_liberica,
      price: '$12',
      name: 'Liberica',
      desc: 'Lorem ipsum dolor sit amet cons ',
      isFavorite: false,
    },
  ],
  my_order_list: [
    {
      id: 1,
      image: APP_IMAGES.ic_robusta,
      price: 40,
      order_status: 0,
      qty: 2,
      name: 'Robusta',
    },
    {
      id: 2,
      image: APP_IMAGES.ic_arabica,
      price: 40,
      order_status: 0,
      qty: 2,
      name: 'Liberica',
    },
    {
      id: 3,
      image: APP_IMAGES.ic_liberica,
      price: 40,
      order_status: 0,
      qty: 2,
      name: 'Robusta',
    },
    {
      id: 4,
      image: APP_IMAGES.ic_juice,
      price: 40,
      order_status: 1,
      qty: 2,
      name: 'Liberica',
    },
    {
      id: 5,
      image: APP_IMAGES.ic_robusta,
      price: 40,
      order_status: 1,
      qty: 2,
      name: 'Cirtus',
    },
    {
      id: 6,
      image: APP_IMAGES.ic_excelsa,
      price: 40,
      order_status: 1,
      qty: 2,
      name: 'Liberica',
    },
    {
      id: 7,
      image: APP_IMAGES.ic_juice,
      price: 40,
      order_status: 1,
      qty: 2,
      name: 'Cirtus',
    },
    {
      id: 8,
      image: APP_IMAGES.ic_coffee,
      price: 40,
      order_status: 1,
      qty: 2,
      name: 'Robusta',
    },
    {
      id: 9,
      image: APP_IMAGES.ic_liberica,
      price: 40,
      order_status: 1,
      qty: 2,
      name: 'Cirtus',
    },
    {
      id: 10,
      image: APP_IMAGES.ic_juice,
      price: 40,
      order_status: 1,
      qty: 3,
      name: 'Liberica',
    },
  ],
  notification_list: [
    {
      id: 1,
      type: 0,
      title: 'Order Delivered',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-22 11:30:10',
    },
    {
      id: 2,
      type: 1,
      title: '20% discount Alert',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-22 13:30:10',
    },
    {
      id: 3,
      type: 2,
      title: 'New Product launch',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-22 15:30:10',
    },
    {
      id: 4,
      type: 0,
      title: 'Order Delivered',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-21 11:30:10',
    },
    {
      id: 5,
      type: 1,
      title: '20% discount Alert',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-21 13:30:10',
    },
    {
      id: 6,
      type: 2,
      title: 'New Product launch',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-21 15:30:10',
    },
    {
      id: 7,
      type: 0,
      title: 'Order Delivered',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-20 11:30:10',
    },
    {
      id: 8,
      type: 1,
      title: '20% discount Alert',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-20 13:30:10',
    },
    {
      id: 9,
      type: 2,
      title: 'New Product launch',
      desc: 'Lorem ipsum dolor sit amet consectetur. Scelerisque',
      created_at: '2024-4-20 15:30:10',
    },
  ],
  cart_list: [
    {
      id: 1,
      image: APP_IMAGES.ic_arabica,
      item_name: 'Arabica',
      ingridients: 'Milk',
      price: 20,
      qty: 1,
    },
    {
      id: 2,
      image: APP_IMAGES.ic_liberica,
      item_name: 'Liberica',
      ingridients: 'Cheese-cream',
      price: 50,
      qty: 2,
    },
    {
      id: 3,
      image: APP_IMAGES.ic_excelsa,
      item_name: 'Excelsa',
      ingridients: 'Ice-cream',
      price: 60,
      qty: 4,
    },
  ],
  checkOutDetails: {
    address: '1910, wien stadt, At',
    card_details: 'Credit or debit',
    cart_list: [
      {
        id: 1,
        image: APP_IMAGES.ic_arabica,
        item_name: 'Arabica',
        ingridients: 'Milk',
        price: 20,
        qty: 1,
      },
      {
        id: 2,
        image: APP_IMAGES.ic_liberica,
        item_name: 'Liberica',
        ingridients: 'Cheese-cream',
        price: 50,
        qty: 2,
      },
      {
        id: 3,
        image: APP_IMAGES.ic_excelsa,
        item_name: 'Excelsa',
        ingridients: 'Ice-cream',
        price: 60,
        qty: 4,
      },
    ],
  },
};
