export const Routes = {
  Splash: 'Splash',
  Intro: 'Intro',
  Login: 'Login',
  Register: 'Register',
  Dashboard: 'Dashboard',
  Home: 'Home',
  Cart: 'Cart',
  Wishlist: 'Wishlist',
  Profile: 'Profile',
  InviteFriend: 'InviteFriend',
  MyOrder: 'MyOrder',
  PrivacyPolicy: 'PrivacyPolicy',
  SettingScreen: 'SettingScreen',
  Notification: 'Notification',
};
